// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from service.djinni

#import <Foundation/Foundation.h>

@interface IPSBinaryRadiomap : NSObject
- (nonnull instancetype)initWithData:(nonnull NSData *)data
                                uuid:(nonnull NSString *)uuid;
+ (nonnull instancetype)binaryRadiomapWithData:(nonnull NSData *)data
                                          uuid:(nonnull NSString *)uuid;

@property (nonatomic, readonly, nonnull) NSData * data;

@property (nonatomic, readonly, nonnull) NSString * uuid;

@end
