// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from path.djinni

#import "IPSCoreNode.h"
#import <Foundation/Foundation.h>

@interface IPSCorePath : NSObject
- (nonnull instancetype)initWithNodes:(nonnull NSArray *)nodes;
+ (nonnull instancetype)corePathWithNodes:(nonnull NSArray *)nodes;

@property (nonatomic, readonly, nonnull) NSArray * nodes;

@end
