// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from path.djinni

#import <Foundation/Foundation.h>

@interface IPSCoreNode : NSObject
- (nonnull instancetype)initWithLatitude:(double)latitude
                               longitude:(double)longitude
                                      id:(int64_t)id
                              neighbours:(nonnull NSArray *)neighbours;
+ (nonnull instancetype)coreNodeWithLatitude:(double)latitude
                                   longitude:(double)longitude
                                          id:(int64_t)id
                                  neighbours:(nonnull NSArray *)neighbours;

@property (nonatomic, readonly) double latitude;

@property (nonatomic, readonly) double longitude;

@property (nonatomic, readonly) int64_t id;

@property (nonatomic, readonly, nonnull) NSArray * neighbours;

@end
