// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from latlong_utils.djinni

#import <Foundation/Foundation.h>
@class IPSILatlong;


@interface IPSILatlongUtils : NSObject

+ (double)getDistanceInMeters:(nullable IPSILatlong *)locationOne
                  locationTwo:(nullable IPSILatlong *)locationTwo;

+ (double)getDistance:(double)firstLat
             firstLon:(double)firstLon
            secondLat:(double)secondLat
            secondLon:(double)secondLon;

+ (nullable IPSILatlong *)updateCoordinates:(nullable IPSILatlong *)positionToUpdate
                                      shift:(double)shift
                                    bearing:(double)bearing;

@end
