// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from fingerprint.djinni

#import <Foundation/Foundation.h>
@class IPSIFingerprint;
@class IPSIGraphPosition;
@class IPSIMeasurement;


@interface IPSIFingerprint : NSObject

+ (nullable IPSIFingerprint *)createFingerprint;

+ (nullable IPSIFingerprint *)createFingerprintWithParams:(nonnull NSArray *)measurements;

+ (nonnull NSString *)createBinaryFingerprint:(nullable IPSIGraphPosition *)graphPosition
                                 measurements:(nonnull NSArray *)measurements;

/**
 *# is it really needed:
 * const get_measurements() : map<string, i_measurement>;
 */
- (void)setMeasurements:(nonnull NSArray *)measurements;

- (int32_t)getMeasurementsCount;

/**# end */
- (nullable IPSIGraphPosition *)getGraphPosition;

- (void)setGraphPosition:(nullable IPSIGraphPosition *)graphPosition;

@end
